### ISSUE TITLE
Error setting up entry Grohe Sense for grohe_sense

### ISSUE THREAD

**Issue by szappanyos** [Flo-Schilli/homeassistant-grohe_sense#10]
`Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 13:07:16 (1 occurrences)
Last logged: 13:07:16

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/__init__.py", line 23, in async_setup_entry
    devices: List[GroheDevice] = await GroheDevice.get_devices(api)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/dto/grohe_device.py", line 77, in get_devices
    appliances = await ondus_api.get_appliances(location.id, room.id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 298, in get_appliances
    return [Appliance.from_dict(appliance) for appliance in data]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable`

**Comment by Flo-Schilli** [comment]
@szappanyos can you just give it another try. It should be fixed now. Problem was, that empty rooms/locations haven't been handled correctly.

**Comment by szappanyos** [comment]
Thank you. It works :D This is the first time I was able to use this integration.

**Comment by Flo-Schilli** [comment]
I'm happy that it's working now and that you're now able to use this integration 😊
