### ISSUE TITLE
Pressure value seems to be wrong

### ISSUE THREAD

**Issue by szappanyos** [Flo-Schilli/homeassistant-grohe_sense#17]
When I looked at the pressure value/graph in the Grohe Sense app the values were different.
This integration might be using average values instead of actual values.
![2 (1)](https://github.com/user-attachments/assets/7809c615-67ce-493f-a66c-3892a34e538c)
![1 (1)](https://github.com/user-attachments/assets/d52de799-6d48-41a2-b31d-f2bfdd0d78e1)

**Comment by Flo-Schilli** [comment]
Hi, I finally found the time to look into this. 
This sensor value is being updated every hour (what you see in the Grohe Sense App)  and I do have these values actually grouped by day not hour, that's why it is looking different.
Will let you know once I implemented another version.

**Comment by Flo-Schilli** [comment]
Seems like the Sensor state is updating more often within an hour than shown inside the Grohe App so that within HA you do have more peaks now than within the app.

**Comment by szappanyos** [comment]
The main issue that bothered me more than the graph was that in Grohe app the current value was 5 bars for example. In HA the value was just slowly rising. Reaching 5 bars only after many many hours.
This prevents me to detect when I have no water (low pressure) and water is back to normal (above 2 bars).

**Comment by Flo-Schilli** [comment]
Okay, so that definitely should be working now. I just merged it into main so you should be able to check on this now. Would be great - that if its fixed for you - you could just close the issue

**Comment by Flo-Schilli** [comment]
Sorry I just moved it to done by accident. If its not fixed for you just reopen it please.

**Comment by szappanyos** [comment]
I can confirm that the fix works. Now I can detect when pressure is low (or no water) and is normal. Thank you
