### ISSUE TITLE
[FIXED] Grohe Blue Home issue [Grohe Sense: No devices or entities]

### ISSUE THREAD

**Issue by daxyorg** [Flo-Schilli/homeassistant-grohe_sense#18]
Hi,

After I selected the component (Grohe sense) and entered my credentials (username/password), I received only this message

<img width="437" alt="Screenshot 2024-09-13 at 20 49 13" src="https://github.com/user-attachments/assets/8a512afb-5f7d-48c7-8f09-32db61f54752">

And after restarting the integration I don't see any sensors or Guard:

<img width="272" alt="Screenshot 2024-09-13 at 20 52 34" src="https://github.com/user-attachments/assets/f7974eb0-553f-478d-9af7-656988630b19">

I checked several times: I add correctly my credentials.
Is it possible to add manual my credentials or token in config file?
Thanks a lot in advance for this repo and help!

**Comment by Flo-Schilli** [comment]
Hi,

in general you directly should see your devices and be able to assign an area where they are located in.
Do you get some errors from the intrgration in the log?
In the Grohe app the Grohe Sense is already assigned a location and room, right?
If you don't get any errors/warnings in the log, it would be really helpful to have the debug output of the integration.

Thanks in advance.

**Comment by daxyorg** [comment]
Hi,

I really appreciate and thank you for the quick response!
I don't received any error messages in logs. But when I activated the debugging mode, deleted and added again new integration, I received this messages:

<img width="587" alt="Screenshot 2024-09-13 at 22 54 39" src="https://github.com/user-attachments/assets/98d5299a-023f-4ad3-9ed2-9311509d01e9">


I have a location called "Acasa" and rooms:

<img width="231" alt="Screenshot 2024-09-13 at 22 56 40" src="https://github.com/user-attachments/assets/aef609f4-1d8c-48eb-a87e-ae8805db5679">

**Comment by Flo-Schilli** [comment]
Thanks for the quick reply.

Do you also have a Grohe Blue Home? Seems like the integration is getting the information of a Grohe Type 104 which is causing it to fail.
If it's like that, can you verify that the blue home is having the same sensor values like the blue professional? Or what is not available in the blue home.
If it's similar, I can add the blue home with the same sensors like the blue professional and upload it to the dev branch within the next few days.

**Comment by daxyorg** [comment]
Ok, yes. Sorry I didn't mention. I have Grohe Blue Home.
Blue Home and professional are almost the same. Professional has an option for big bottle CO2.
Update: Now everything is OK. I added in ondus_types.py Grohe Blue Home with type 104. 
May be there are some additional editions in other files, but now I see this:

<img width="408" alt="Screenshot 2024-09-13 at 23 46 19" src="https://github.com/user-attachments/assets/f42f38e4-e4e3-464f-89db-dc9fedbbe06a">

<img width="363" alt="Screenshot 2024-09-13 at 23 48 33" src="https://github.com/user-attachments/assets/0a7aa8d5-adee-4280-86a5-396b2ebcd92b">

**Comment by Flo-Schilli** [comment]
That's great that you're seeing the other ones right now already after adding the 104 👍
I'm gonna enhance the other files for the blue. Would you mind testing it afterwards, as I'm not having a Grohe Blue Home.

**Comment by daxyorg** [comment]
Yes, of course. With pleasure I will test.

**Comment by Flo-Schilli** [comment]
On develop branch I just fully added the Blue Home with the same settings like the Blue Professional. 
It could be that it's returning you an error. If it is, can you please post the values from within the debug log after `Got the following details for Grohe Blue appliance` and without the appliance ID.

**Comment by daxyorg** [comment]
I sent the log in develop.

**Comment by Flo-Schilli** [comment]
Thanks for the log. It is really strange that it is saying that the Grohe Blue Home is not within the Enum but in develop it is. That's the reason why you're getting the unknown on all other sensor values.
Can you please check that the enum is having the 104 in the ondus_types.py.

**Comment by daxyorg** [comment]
> Thanks for the log. It is really strange that it is saying that the Grohe Blue Home is not within the Enum but in develop it is. That's the reason why you're getting the unknown on all other sensor values. Can you please check that the enum is having the 104 in the ondus_types.py.

After 10-15 minutes data was extracted:

<img width="449" alt="Screenshot 2024-09-14 at 9 25 28" src="https://github.com/user-attachments/assets/aa4a7d79-111d-4033-9318-d11067b48964">

**Comment by Flo-Schilli** [comment]
And are you seeing the blue home as well listed as a device within the intrgration?

**Comment by daxyorg** [comment]
> And are you seeing the blue home as well listed as a device within the intrgration?

Not yet. Just Guard and sensors.

**Comment by Flo-Schilli** [comment]
In general it should be there once the integration is running okay. Are there any other errors in the Log. Is still the 104 error active even with the latest commit from develop?

**Comment by daxyorg** [comment]
> In general it should be there once the integration is running okay. Are there any other errors in the Log. Is still the 104 error active even with the latest commit from develop?

I reinstall a repo and edited the 4 files after that I sign-in and visualise a guard and sensors, in logs there is no errors, only these warnings:

2024-09-14 10:01:00.475 WARNING (MainThread) [custom_components.xxxxx.sensor] Unrecognized appliance <custom_components.grohe_sense.dto.grohe_device.GroheDevice object at 0x7f54XXXX30>, ignoring.
2024-09-14 10:01:00.706 WARNING (MainThread) [custom_components.grohe_sense.api.ondus_api] URL https://idp2-apigw.cloud.grohe.com/v3/iot/locations/XXXXXXX/rooms/XXXXXX/appliances/xxxxxxx-a55d-xxxx-xxxx-xxxxxxxxxx/data/aggregated?from=2024-09-14 **returned status code 405**

Maybe this status code 405 means something?

**Comment by Flo-Schilli** [comment]
Can you please activate the debug logging for the integration, there should then be more information available within the logs. 
Can you also please verify that the appliance for which you're gettting the 405 is the Grohe Blue Home or if it is another device. In the debug log you should see `Got the following details for Grohe Blue appliance` somewhen after starting the integration, that output would be interesting for me.
Also right after the start of the integration you should see a message similar to this:
`Found in location XXXXXXX and room XXXXXXX the following appliance: XXXXXXX from type 103 with name SenseGuard` which will provide you the information to check in the URL for the aggregated data if it's the Grohe Blue Home or not.
Are you checking out the repository and moving the files manually to HA or are you using HACS? 
Please also use the latest develop branch as I just formated the debug log to match with this comment

**Comment by daxyorg** [comment]
Hello, 

Sorry for the delay.
What I do: copy and paste new grohe_sense with debug mode.
The log is with 3435 rows.
Please, let me know where can I find "Got the following details for Grohe Blue appliance", because in my HA Yellow, I know only for these logs:

<img width="587" alt="Screenshot 2024-09-16 at 9 41 13" src="https://github.com/user-attachments/assets/bdaec3a1-e58b-4f88-84e2-8d8ca87a500f">

And there is no info about it. 
In log also cannot find info about location nr or rooms.

Thanks in advance!

**Comment by Flo-Schilli** [comment]
Hi,

after you have changed the log level to debug you should be able to see (and probably have to scroll a little bit) it under Settings -> System -> Logs and click there on 'Load Full Logs'.
Best would be, before doing this - and for you to search less - restart the home assistant before. Quite at the beginning - after all integrations loaded successfully - you should see it and should also be able to search for the above mentioned value within the logs

**Comment by daxyorg** [comment]
Hi,

What I did: fully prenatal HA Yellow, then just added the folder grohe_sense (developer) in custom_components.
I think the case is closed, because now I see the info below.
I don't get any errors anymore (the debug log is activated).
If you think I can be useful with other tests, please write.

<img width="329" alt="Screenshot 2024-09-17 at 13 46 06" src="https://github.com/user-attachments/assets/85ed329c-1482-4d28-8de0-3fe7451596e2">

**Comment by Flo-Schilli** [comment]
Thats great that it is working now 👍 also pushed to Main already 😊 thanks for the feedback
