### ISSUE TITLE
Valve state is not updated in HA when changed in the app

### ISSUE THREAD

**Issue by barth11** [Flo-Schilli/homeassistant-grohe_sense#20]
Hi,
When I close the valve in the app, the HA state is not updated. Vice versa it works. When I close the valve in HA the state in the app is updated accordingly.
Can anyone reproduce this or is it working?

B.

**Comment by Flo-Schilli** [comment]
Hi @barth11,

it should be fixed now and I also tested it on my side. The valve state update is done every 60secs, so there is a little delay expected.
Interestingly the Grohe app itself is only force refreshing the valve state on my side, so if I'm at the statistics side already, they are not updating the state within the app.
If you confirm that the behavior is now fixed, please feel free to close the ticket.
