### ISSUE TITLE
Sensors issue

### ISSUE THREAD

**Issue by daxyorg** [Flo-Schilli/homeassistant-grohe_sense#22]
> Hi,
> 
> 
> 
> After changes in this file: [custom_components/grohe_sense/entities/grohe_sense_update_coordinator.py](https://github.com/Flo-Schilli/homeassistant-grohe_sense/commit/3fd9423b92a09672cf71e37ca4deb14b156a125c#diff-600096c24338ba8a202a35ab4317333b2a23f8ec952fc7c78d9c93e6580aacf5)
> 
> 
> 
> I don't received data from sensors. Only data from Grohe Blue Home is ok.
> 
> 
> 
> <img width="442" alt="Screenshot 2024-09-18 at 18 14 20" src="https://github.com/user-attachments/assets/3ec92f59-a81a-46e7-b9f8-d2059c09f041">
> 
> 
> 
> <img width="444" alt="Screenshot 2024-09-18 at 18 24 10" src="https://github.com/user-attachments/assets/b2016fe9-5a3d-4ebc-a1fa-753e1545d8e4">
> 
> 
> 
> 
> 
> I made double check, when I use the old file grohe_sense_update_coordinator.py everything it's ok. 

 _Originally posted by @daxyorg in [3fd9423](https://github.com/Flo-Schilli/homeassistant-grohe_sense/commit/3fd9423b92a09672cf71e37ca4deb14b156a125c#commitcomment-146884131)_

**Comment by Flo-Schilli** [comment]
Hi @daxyorg :wave: 
can you please verify that it is working again in the newest version (0.9.8)
Thanks

**Comment by daxyorg** [comment]
> Hi @daxyorg 👋 can you please verify that it is working again in the newest version (0.9.8) Thanks

Thanks for the fast response! Now everything works.

**Comment by daxyorg** [comment]
case closed
