### ISSUE TITLE
Integration "Last" Values

### ISSUE THREAD

**Issue by DeepflashX** [Flo-Schilli/homeassistant-grohe_sense#34]
Hello Flo,

could you integrate these values:
details.data_latest.withdrawals.waterconsumption --> last water consumption
details.data_latest.withdrawals.maxflowrate --> last max flowrate
details.data_latest.average_monthly_consumption --> average consumption monthly
details.data_latest.average_daily_consumption --> average consumption daily 
details.data_latest.daily_consumption --> up to date consumption for the day

I added those in Node Red Integration and they seem to be helpful / usefu.

Best regards,
Matthias

**Comment by Flo-Schilli** [comment]
Hi Matthias :wave: 

thanks for the input. I'll check and implement them. Will inform you once it's finished :smile:

**Comment by DeepflashX** [comment]
Hey Flo,

Looks good, thx for Integration.
do you have an idea, how I can toggle the grohe valve from Loxone? I do have the pyloxone Integration but I dont know how to link that..

**Comment by Flo-Schilli** [comment]
Values are so far integrated. 
Discussion with Loxone is continued in #42
