### ISSUE TITLE
Some Sensors are unknown

### ISSUE THREAD

**Issue by patricknitsch** [Flo-Schilli/homeassistant-grohe_sense#35]
Hi,

since a few days I only get new states for a few entities. See the picture. 

![image](https://github.com/user-attachments/assets/68e63e3b-a0c6-4af2-9f74-c1ca27ae8559)

Do you already had this problem? Can I do something?

Many greets!

**Comment by Flo-Schilli** [comment]
Hi,

all looks normal on my side for now.

![IMG_20241203_224841.jpg](https://github.com/user-attachments/assets/9b111d9d-089a-4c78-ad7b-1532b5a809fe)

Which version of the custom component are you using?
Are there some log entries from the component available which would give a hint?

Thanks already for the info 😊

**Comment by patricknitsch** [comment]
Hi, 

Version 0.9.13.

The only errors in the logs I see are

`Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:944
Erstmals aufgetreten: 3. Dezember 2024 um 02:06:46 (17 Vorkommnisse)
Zuletzt protokolliert: 3. Dezember 2024 um 02:22:54

Update for valve.grohe_sense_guard_valve fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/resolver.py", line 105, in resolve
    resp = await self._resolver.getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiodns.error.DNSError: (12, 'Timeout while contacting DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 964, in _resolve_host
    await future
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/resolver.py", line 114, in resolve
    raise OSError(None, msg) from exc
OSError: [Errno None] Timeout while contacting DNS servers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/grohe_sense/entities/grohe_sense_guard_valve.py", line 53, in async_update
    command_response = await self._auth_session.get_appliance_command(self._device.location_id,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 460, in get_appliance_command
    data = await self.__get(url)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 212, in __get
    response = await self._session.get(url=url, headers={
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 538, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1341, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host idp2-apigw.cloud.grohe.com:443 ssl:default [Timeout while contacting DNS servers]
`

**Comment by Flo-Schilli** [comment]
This DNS error is kinda strange but the log shouldn't have anything to do with the unknown values, as the appliance command does return other data.

Are you having any custom DNS server running? Or are you using the one from your provider? Is a restart of HA showing any changes towards this behaviour? 
I hope that by tomorrow I will have the time to test some stuff on my PC.

Will let you know afterwards 😊

**Comment by Flo-Schilli** [comment]
Hey, can you please try it with the newest version.

Also in the debug log there should be the following entry before getting the data needed: `[custom_components.grohe_sense.entities.grohe_sense_update_coordinator] Get actual measurement`

Can you please check if somewhere around there an error is shown.

**Comment by patricknitsch** [comment]
No there no errors. But what I found in the logs is this:

temperature=None, humidity=None, flow_rate=None, pressure=4.7, temperature_guard=14.5, battery=None, 

This three entities are unknown.

**Comment by Flo-Schilli** [comment]
Where are you getting these values from. I'm not getting that information within the debug logs on my side. Therefore it would be great to have a full debug log for one update request of the component.

**Comment by Flo-Schilli** [comment]
You can also get the required information/return values when installing the following branch:
https://github.com/Flo-Schilli/homeassistant-grohe_sense/tree/feature/actions

And then going to the Developer tools and adding the device name of the device like it is shown in the integration.
![Screenshot From 2024-12-05 22-40-22](https://github.com/user-attachments/assets/0e88b85d-f42a-4fae-8770-7e3b29d49077)

Can you please send me the output of it afterwards :smile:

**Comment by patricknitsch** [comment]
How can I change the branch in HA?

**Comment by Flo-Schilli** [comment]
Have you downloaded it via HACS as a custom repository or how have you added it to HA?

**Comment by patricknitsch** [comment]
Via HACS

**Comment by Flo-Schilli** [comment]
I am always - when switching branches, directly upload them via SSH to the device and uodafe it in that way. Therefore I cannot tell you how to do it via HACS. Maybe the HACS side will give more infos to that. Maybe you can have a look their.

**Comment by patricknitsch** [comment]
I will test it via ssh. Do you have some instructions how I can do it?

**Comment by patricknitsch** [comment]
After changing the branch I got some new entities. But flow rate, pressure and temperature are still unknown.
What I found in the developer tools with "get appliance details":

`appliance_id: da9f8903-18a9-4e8c-bc95-d3da3266b7ad
installation_date: "2024-05-27T13:17:25.000+02:00"
name: Grohe Sense Guard
serial_number: 315a31363031304331383645303030323030303430303034
type: 103
version: 02.05.Z22.0400.0101
tdt: "2024-12-10T16:00:27.000+01:00"
timezone: 60
config:
  thresholds:
    - quantity: flowrate
      type: min
      value: 3
      enabled: false
    - quantity: flowrate
      type: max
      value: 50
      enabled: true
    - quantity: pressure
      type: min
      value: 2
      enabled: false
    - quantity: pressure
      type: max
      value: 8
      enabled: false
    - quantity: temperature_guard
      type: min
      value: 5
      enabled: false
    - quantity: temperature_guard
      type: max
      value: 45
      enabled: false
  measurement_period: 900
  measurement_transmission_intervall: 900
  measurement_transmission_intervall_offset: 1
  action_on_major_leakage: 1
  action_on_minor_leakage: 1
  action_on_micro_leakage: 0
  monitor_frost_alert: true
  monitor_lower_flow_limit: false
  monitor_upper_flow_limit: true
  monitor_lower_pressure_limit: false
  monitor_upper_pressure_limit: false
  monitor_lower_temperature_limit: false
  monitor_upper_temperature_limit: false
  monitor_major_leakage: true
  monitor_minor_leakage: true
  monitor_micro_leakage: true
  monitor_system_error: false
  monitor_btw_0_1_and_0_8_leakage: true
  monitor_withdrawel_amount_limit_breach: true
  detection_interval: 11250
  impulse_ignore: 10
  time_ignore: 20
  pressure_tolerance_band: 10
  pressure_drop: 50
  detection_time: 30
  action_on_btw_0_1_and_0_8_leakage: 1
  action_on_withdrawel_amount_limit_breach: 1
  withdrawel_amount_limit: 300
  sprinkler_mode_start_time: 0
  sprinkler_mode_stop_time: 1439
  sprinkler_mode_active_monday: true
  sprinkler_mode_active_tuesday: true
  sprinkler_mode_active_wednesday: true
  sprinkler_mode_active_thursday: true
  sprinkler_mode_active_friday: true
  sprinkler_mode_active_saturday: true
  sprinkler_mode_active_sunday: true
role: owner
registration_complete: true
calculate_average_since: "2024-05-27T11:17:25.000Z"
snooze_status: NON_EXISTENT
status:
  - type: update_available
    value: 0
  - type: wifi_quality
    value: 3
  - type: connection
    value: 1
installer:
  name: ""
  email: ""
  phone: ""
data_latest:
  measurement:
    flowrate: 0
    pressure: 4.7
    temperature_guard: 14.5
    timestamp: "2024-12-01T05:53:31.000+01:00"
  average_monthly_consumption: 5126
  daily_cost: 0.25
  daily_consumption: 59
  average_daily_consumption: 171
  withdrawals:
    starttime: "2024-12-10T15:46:39.000+01:00"
    stoptime: "2024-12-10T15:47:41.000+01:00"
    waterconsumption: 8.9
    maxflowrate: 11.4
notifications: []
command:
  temp_user_unlock_on: false
  reason_for_change: 0
  pressure_measurement_running: false
  buzzer_on: false
  buzzer_sound_profile: 2
  valve_open: true
  measure_now: false
`

**Comment by patricknitsch** [comment]
We can close the issue. It was not a problem with your integration. It was a problem with my device. After device restart all values are now correct.
