### ISSUE TITLE
Error with new not-installed device

### ISSUE THREAD

**Issue by jlatvala** [Flo-Schilli/homeassistant-grohe_sense#46]
I have a new Grohe Sense Guard, which I added into Grohe app/account yesterday. 
At the same time I also tested this HA integration (works :) ).

However, the Sense Guard is not physically installed yet (will be installed in January) so most of its sensors have value "Unknown".

Grohe Sense app shows that my Sense Guard version is 02.05. (I kept the device online few hours but it did not upgrade its FW in that time).

Model is 22500LN0 
(bought in Finland) 

Not sure if you want to fix this because, I guess, the problem goes away when there will be real wate consumption.

Anyways, now, after about 15 hours, it has written this into HA log about 230 times:
```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/grohe_sense/entities/grohe_sense_guard_latest_data.py", line 54, in _handle_coordinator_update
    self._value = self._coordinator.data.latest_data.withdrawals.waterconsumption
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'waterconsumption'

```

**Comment by Flo-Schilli** [comment]
Hi @jlatvala :wave: 

could you try with the - a few minutes age released - beta version. I guess these problems than should be gone.
It's installable via HACS (once you added the custom repo) and selecting a different version. Otherwise the develop branch can be used :smile:

**Comment by jlatvala** [comment]
Installed the beta version, will report back in few hours

**Comment by jlatvala** [comment]
Now, 5 hours later, no errors logged
--> fixed in beta

**Comment by Flo-Schilli** [comment]
Great that it's working for you :smile: 

I'm gonna close the ticket and within the next few days I'm gonna release the beta as stable version :smile:

**Comment by Flo-Schilli** [comment]
Hey @jlatvala 
the new version is released with the fix inside :smile:
