### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by sven-s** [Flo-Schilli/homeassistant-grohe_sense#53]
I installed the latest version 0.21.0. After that I removed the found device (according to the release notes) and try to add my device back again. After that I got this error:

```
TypeError: cannot unpack non-iterable NoneType object
    await api.login(entry.data.get('username'), entry.data.get('password'))
  File "/config/custom_components/grohe_sense/api/ondus_api.py", line 286, in login
    cookie, action = await self.__get_oidc_action()
    ^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

How to fix this?

**Comment by Flo-Schilli** [comment]
Hi 👋 

can you try the following steps:
- Remove device/integration 
- restart HA
- add again and check if it is working 

Sorry for the inconvenience

**Comment by sven-s** [comment]
That worked. Thanks!
